# Generated by Django 4.2.4 on 2023-08-08 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('NICno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('street_add', models.CharField(max_length=200)),
                ('dob', models.DateTimeField()),
                ('date_of_join', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 2, 14, 8, 420833))),
            ],
        ),
    ]
