# Generated by Django 4.2.4 on 2023-08-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customer_date_of_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_join',
        ),
    ]
