# Generated by Django 4.2.4 on 2023-08-23 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_customer_date_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=268, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 23, 46, 283742)),
        ),
    ]
