# Generated by Django 4.2.4 on 2023-09-04 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_customer_date_of_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.datetime(2023, 9, 4, 13, 15, 17, 248921))),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('buying', models.IntegerField()),
                ('discp', models.TextField(null=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2023, 9, 4, 13, 15, 17, 248921))),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 13, 15, 17, 197964)),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2023, 9, 4))),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders')),
                ('pID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clsResn', models.TextField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders')),
            ],
        ),
    ]
