# Generated by Django 4.2.4 on 2023-09-04 08:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders_products_alter_customer_date_of_join_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 13, 18, 47, 282867)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 13, 18, 47, 327841)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 13, 18, 47, 326842)),
        ),
    ]
