# Generated by Django 4.2.4 on 2023-09-05 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_products_p_img_alter_customer_date_of_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sell',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 1, 2, 4, 520769)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 1, 2, 4, 558521)),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 1, 2, 4, 558521)),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 6)),
        ),
    ]
